plugins:
  - stylelint-prettier
  - stylelint-order
  - stylelint-scss

rules:
  prettier/prettier: true
  scss/at-rule-no-unknown: true
  scss/at-import-no-partial-leading-underscore: true
  color-hex-length: 'short'
  color-no-invalid-hex: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  media-feature-name-no-unknown: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  property-no-vendor-prefix: true
  rule-empty-line-before:
    ['always', { except: ['first-nested', 'after-single-line-comment'] }]
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: 'single'
  selector-pseudo-element-no-unknown:
    [true, { ignorePseudoElements: ['/deep/'] }]
  unit-no-unknown: true
  value-no-vendor-prefix: true
  order/properties-alphabetical-order: true
  order/order:
    [
      'custom-properties',
      'at-rules',
      'at-variables',
      'dollar-variables',
      'declarations',
      { type: 'at-rule', name: 'media' },
      'rules',
      { type: 'at-rule', name: 'at-root' },
    ]
