name: Publish

on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: make ${{ github.ref_name }}

      - name: Check in Version
        run: |
          version=$(cat package.json | jq -r .version)
          git config --local user.name "that70chris"
          git config --local user.email "chris@bailey.mx"
          git commit -am "v$version"
          git push -f origin :${{ github.ref_name }}
          git push -f origin HEAD:main
          git tag $version
          git push --tags
