name: Publish

on:
  push:
    branches:
      - major
      - minor
      - patch

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build the css
        run: make css

      - name: Build the injections
        run: make injections

      - name: Build the tokens
        run: make tokens

      - name: Publish to VSCE
        run: npx vsce publish --no-dependencies ${{ github.ref_name }}

      - name: Check in Version
        run: |
          version=$(cat package.json | jq -r .version)
          git config --local user.name "that70chris"
          git config --local user.email "chris@bailey.mx"
          git commit -am "v$version"

          git push -f origin :${{ github.ref_name }}
          git push -f origin HEAD:main
          git tag $version
          git push --tags
